# This is a basic workflow to help you get started with Actions

name: learn-github-actions-uipath
# Controls when the workflow will run
on: [push]
# Allows you to run this workflow manually from the Actions tab
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple job called "print-information", "publish-uipath-package", "test-uipath-package" etc.
  print-information:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}." 
      
  cleaner:
    runs-on: ubuntu-latest
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"

  build-uipath-nuget-package:
    # You should be able to run on windows 2019 or windows latest
    runs-on: windows-latest
    steps: 
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: Build Nuget Package
        shell: pwsh
        run: ${{ github.workspace }}\scripts\UiPathPack.ps1 ${{ github.workspace }}\project.json -destination_folder ${{ github.workspace }}\package -autoVersion
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: NugetPackage
          path: ${{ github.workspace }}/Package
      
  publish-uipath-nuget-package:
  # You should be able to run on windows 2019 or windows latest
    needs: build-uipath-nuget-package
    runs-on: windows-latest
    env:
      # Replace with your Orchestrator Values 
      PROJECT_NAME: GitHub_Uipath_Example                         
      PROJECT_FOLDER: ${{ github.action_path }}
      ORCH_URL: https://cloud.uipath.com/RPABOTSWORLD/DEV
      ORCH_TENANT: ${{ secrets.UIPATHTENANTNAME }}
      ORCH_CLIENT_ID: ${{ secrets.UIPATHCLIENTID }}
      ORCH_USER_KEY: ${{ secrets.UIPATHUSERKEY }}
      ORCH_ACC_NAME: ${{ secrets.UIPATHACCOUNTNAME }}
    steps: 
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
            name: NugetPackage
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: Publish Nuget Package
        shell: pwsh
        run: ${{ github.workspace }}\scripts\UiPathDeploy.ps1 NugetPackage ${{env.ORCH_URL}} ${{env.ORCH_TENANT}} -UserKey ${{env.ORCH_USER_KEY}} -account_name ${{env.ORCH_ACC_NAME}}